version: '3'
services:
  mysqldb:
    image: 'mysql:5.7'
    ports:
     - 3306:3306
    environment:
     - MYSQL_ROOT_PASSWORD=root
     - MYSQL_DATABASE=tpachato
     - MYSQL_PASSWORD=
    volumes:
     - /home/mysql/data:/var/lib/mysql
  springboot-docker-container:
    image: mourad1998/tpachatmagasin:v1
    ports:
     - 8089:8089
    environment:
        - spring.datasource.url=jdbc:mysql://mysqldb:3306/tpachato?createDatabaseIfNotExist=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    build:
      context: "./"
      dockerfile: "DockerFile"
    depends_on:
      - mysqldb